"""Curated live dataset and merged seed data from InternRadar and Scholarship Tracker Pro."""

from __future__ import annotations
from typing import Any

SEED_OPPORTUNITIES: list[dict[str, Any]] = [
    {
        "id": "intern-001",
        "category": "internship",
        "title": "Software Engineering Intern (Summer 2026/2027)",
        "company": "Google",
        "institution_or_company": "Google",
        "location": "Mountain View, CA / Remote",
        "country": "USA",
        "link": "https://careers.google.com/jobs/results/?distance=50&employment_type=INTERN&q=Software%20Engineering",
        "source": "Google Careers",
        "deadline": "2026-11-15",
        "status": "Upcoming",
        "degree_level": "BSc / MSc",
        "funding_type": "Paid",
        "research_domain": "Software Engineering, Distributed Systems",
        "stipend_amount": "$55 - $65 / hour + Housing Stipend",
        "requirements": "Pursuing BS/MS in CS or related field. Proficiency in C++, Java, or Python.",
        "priority": "Top",
        "match_score": 98,
        "posted_date": "2026-08-20",
        "keyword": "software engineering, distributed systems, python, c++",
        "description": "Join Google's engineering team to build scalable systems, cloud platforms, and user-facing tools used by billions worldwide."
    },
    {
        "id": "intern-002",
        "category": "internship",
        "title": "AI & Deep Learning Research Intern",
        "company": "Microsoft Research",
        "institution_or_company": "Microsoft",
        "location": "Redmond, WA / Cambridge, UK",
        "country": "USA",
        "link": "https://www.microsoft.com/en-us/research/careers/",
        "source": "Microsoft Careers",
        "deadline": "2026-10-31",
        "status": "Open",
        "degree_level": "BSc / MSc / PhD",
        "funding_type": "Paid",
        "research_domain": "Artificial Intelligence, LLMs, NLP",
        "stipend_amount": "$9,500 / month + Relocation",
        "requirements": "Experience with PyTorch, Transformer architectures, and research publications or strong projects.",
        "priority": "Top",
        "match_score": 96,
        "posted_date": "2026-08-15",
        "keyword": "ai, machine learning, deep learning, pytorch, nlp",
        "description": "Collaborate with world-renowned scientists to develop next-generation foundation models, reinforcement learning, and multimodal AI systems."
    },
    {
        "id": "intern-003",
        "category": "internship",
        "title": "Autopilot & Robotics Engineering Intern",
        "company": "Tesla",
        "institution_or_company": "Tesla",
        "location": "Palo Alto, CA",
        "country": "USA",
        "link": "https://www.tesla.com/careers/search/?query=internship%20autopilot",
        "source": "Tesla Careers",
        "deadline": "2026-12-01",
        "status": "Upcoming",
        "degree_level": "BSc / MSc",
        "funding_type": "Paid",
        "research_domain": "Robotics, Computer Vision, Autonomous Vehicles",
        "stipend_amount": "$48 - $58 / hour + Relocation",
        "requirements": "Strong C++ and Python skills. Background in robotics kinematics, SLAM, or deep neural networks for vision.",
        "priority": "Top",
        "match_score": 95,
        "posted_date": "2026-08-22",
        "keyword": "robotics, computer vision, slam, autonomous vehicles, c++",
        "description": "Work on the cutting edge of Full Self-Driving (FSD) and the Optimus humanoid robot neural network stack."
    },
    {
        "id": "intern-004",
        "category": "internship",
        "title": "CERN Summer Student Programme 2027",
        "company": "CERN",
        "institution_or_company": "CERN",
        "location": "Geneva",
        "country": "Switzerland",
        "link": "https://careers.cern/summer-student-programme",
        "source": "CERN Official",
        "deadline": "2027-01-31",
        "status": "Upcoming",
        "degree_level": "BSc / MSc",
        "funding_type": "Fully Funded",
        "research_domain": "Applied Physics, High Performance Computing",
        "stipend_amount": "90 CHF / day living allowance + Travel costs covered",
        "requirements": "Undergraduate or Master's student in Physics, Computing, Mathematics, or Engineering.",
        "priority": "Top",
        "match_score": 96,
        "posted_date": "2026-08-10",
        "keyword": "physics, high performance computing, distributed computing, cern",
        "description": "Join multidisciplinary teams at CERN working on LHC data analysis, distributed grid computing, and detector systems."
    },
    {
        "id": "intern-005",
        "category": "internship",
        "title": "Research & Alignment Intern",
        "company": "OpenAI",
        "institution_or_company": "OpenAI",
        "location": "San Francisco, CA / Hybrid",
        "country": "USA",
        "link": "https://openai.com/careers/search/?department=research",
        "source": "OpenAI Careers",
        "deadline": "2026-11-30",
        "status": "Open",
        "degree_level": "MSc / PhD",
        "funding_type": "Paid",
        "research_domain": "AI Safety, Reinforcement Learning, Foundation Models",
        "stipend_amount": "$60 - $70 / hour + Benefits",
        "requirements": "Strong mathematical foundation, experience training large language models, Python/PyTorch proficiency.",
        "priority": "Top",
        "match_score": 97,
        "posted_date": "2026-08-18",
        "keyword": "ai safety, llm, rlhf, deep learning, python",
        "description": "Work directly with core researchers on frontier AI safety, interpretability, reasoning, and synthetic data generation."
    },
    {
        "id": "intern-006",
        "category": "internship",
        "title": "Embedded Systems & Firmware Intern",
        "company": "Apple",
        "institution_or_company": "Apple",
        "location": "Cupertino, CA",
        "country": "USA",
        "link": "https://jobs.apple.com/en-us/search?search=Internship&team=hardware-engineering",
        "source": "Apple Jobs",
        "deadline": "2026-10-15",
        "status": "Closes Soon",
        "degree_level": "BSc / MSc",
        "funding_type": "Paid",
        "research_domain": "Embedded Systems, Firmware, IoT, Hardware",
        "stipend_amount": "$52 - $62 / hour + Housing",
        "requirements": "Knowledge of C, microcontrollers (ARM Cortex, RISC-V), low-level protocols (I2C, SPI, UART).",
        "priority": "Top",
        "match_score": 95,
        "posted_date": "2026-08-05",
        "keyword": "embedded, firmware, iot, microcontrollers, c, hardware",
        "description": "Develop low-power sensor drivers, power management firmware, and hardware-software interfaces for next-generation devices."
    },
    {
        "id": "intern-007",
        "category": "internship",
        "title": "Software Engineering & AI Intern",
        "company": "Brain Station 23",
        "institution_or_company": "Brain Station 23",
        "location": "Dhaka, Bangladesh / Hybrid",
        "country": "Bangladesh",
        "link": "https://brainstation-23.com/career/",
        "source": "BDJobs / Company Portal",
        "deadline": "2026-09-30",
        "status": "Open",
        "degree_level": "BSc",
        "funding_type": "Paid",
        "research_domain": "Full Stack, AI Integration, Web & Mobile",
        "stipend_amount": "BDT 20,000 - 30,000 / month",
        "requirements": "Final year CSE/EEE student. Proficiency in JavaScript/TypeScript, React, Python/Django, or Node.js.",
        "priority": "High",
        "match_score": 90,
        "posted_date": "2026-08-25",
        "keyword": "full stack, react, python, nodejs, bangladesh, web",
        "description": "Work with agile engineering teams on international fintech, enterprise ERP, and AI-powered client solutions."
    },
    {
        "id": "ra-001",
        "category": "ra",
        "title": "Graduate Research Assistant: Robot Manipulation & Learning",
        "company": "MIT CSAIL",
        "institution_or_company": "Massachusetts Institute of Technology (MIT)",
        "location": "Cambridge, MA",
        "country": "USA",
        "link": "https://groups.csail.mit.edu/locomotion/",
        "source": "MIT Lab Website",
        "deadline": "2026-12-15",
        "status": "Open",
        "degree_level": "MSc / PhD",
        "funding_type": "Fully Funded",
        "professor_name": "Prof. Russ Tedrake",
        "lab_name": "Robot Locomotion Group (CSAIL)",
        "lab_website": "https://groups.csail.mit.edu/locomotion/",
        "research_domain": "Robotics, Reinforcement Learning, Controls",
        "stipend_amount": "$3,800 / month + 100% Tuition Waiver + Health Insurance",
        "requirements": "Strong background in linear algebra, controls, Python/Drake, and robotics simulators.",
        "priority": "Top",
        "match_score": 98,
        "assistantship": "RA",
        "competition": "High",
        "posted_date": "2026-08-19",
        "keyword": "robotics, reinforcement learning, controls, drake, mit, ra",
        "description": "Seeking motivated Graduate RA to research tactile dexterity and neural policy representations for robotic manipulation."
    },
    {
        "id": "ra-002",
        "category": "ra",
        "title": "Research Assistant in 3D Computer Vision & Embodied AI",
        "company": "Stanford Vision and Learning Lab (SVL)",
        "institution_or_company": "Stanford University",
        "location": "Stanford, CA",
        "country": "USA",
        "link": "https://svl.stanford.edu/",
        "source": "Stanford SVL",
        "deadline": "2026-11-30",
        "status": "Open",
        "degree_level": "BSc / MSc / PhD",
        "funding_type": "Fully Funded",
        "professor_name": "Prof. Fei-Fei Li / Prof. Silvio Savarese",
        "lab_name": "Stanford Vision and Learning Lab",
        "lab_website": "https://svl.stanford.edu/",
        "research_domain": "Computer Vision, Embodied AI, 3D Vision, NeRF",
        "stipend_amount": "$4,200 / month + Full Tuition Coverage",
        "requirements": "Proficiency in PyTorch, 3D Gaussian Splatting/NeRF, and publication record in CVPR/ICCV.",
        "priority": "Top",
        "match_score": 96,
        "assistantship": "RA",
        "competition": "High",
        "posted_date": "2026-08-16",
        "keyword": "computer vision, embodied ai, nerf, 3d vision, stanford, ra",
        "description": "Participate in frontier research on foundational vision models for spatial reasoning and simulated embodied environments."
    },
    {
        "id": "ra-003",
        "category": "ra",
        "title": "Research Assistant in Autonomous Systems & SLAM",
        "company": "Oxford Robotics Institute (ORI)",
        "institution_or_company": "University of Oxford",
        "location": "Oxford",
        "country": "United Kingdom",
        "link": "https://ori.ox.ac.uk/about-us/careers/",
        "source": "Oxford ORI Portal",
        "deadline": "2027-01-10",
        "status": "Upcoming",
        "degree_level": "MSc / PhD",
        "funding_type": "Full Tuition + Stipend",
        "professor_name": "Prof. Paul Newman / Prof. Ingmar Posner",
        "lab_name": "Applied AI Lab (AAL)",
        "lab_website": "https://ori.ox.ac.uk/",
        "research_domain": "Autonomous Vehicles, SLAM, LiDAR, Spatial AI",
        "stipend_amount": "\u00a319,500 / year (Tax-free) + Full UK/EU Tuition Waiver",
        "requirements": "First Class degree in Engineering/CS. Strong C++, ROS2, and point cloud processing background.",
        "priority": "Top",
        "match_score": 95,
        "assistantship": "RA",
        "competition": "High",
        "posted_date": "2026-08-21",
        "keyword": "slam, robotics, lidar, autonomous systems, oxford, ra",
        "description": "Develop robust multi-modal perception pipelines in adverse weather conditions for off-road and urban autonomous fleets."
    },
    {
        "id": "ra-004",
        "category": "ra",
        "title": "Research Assistant: Large Multimodal NLP & Reasoning",
        "company": "NUS AI Institute & WING Lab",
        "institution_or_company": "National University of Singapore (NUS)",
        "location": "Singapore",
        "country": "Singapore",
        "link": "https://wing.comp.nus.edu.sg/",
        "source": "NUS Faculty Page",
        "deadline": "2026-10-31",
        "status": "Open",
        "degree_level": "BSc / MSc / PhD",
        "funding_type": "Fully Funded",
        "professor_name": "Prof. Min-Yen Kan",
        "lab_name": "Web Information Retrieval / NLP Group (WING)",
        "lab_website": "https://wing.comp.nus.edu.sg/",
        "research_domain": "NLP, Information Retrieval, Multimodal LLMs",
        "stipend_amount": "SGD 3,500 - 4,500 / month + Medical benefits",
        "requirements": "Strong track record in deep learning for NLP (Transformers, LLM evaluation). Experience with Hugging Face.",
        "priority": "Top",
        "match_score": 94,
        "assistantship": "RA",
        "competition": "Medium",
        "posted_date": "2026-08-14",
        "keyword": "nlp, llm, information retrieval, transformers, singapore, nus, ra",
        "description": "Investigate multilingual reasoning capabilities and hallucination mitigation in scientific question-answering systems."
    },
    {
        "id": "ra-005",
        "category": "ra",
        "title": "Research Assistant in Edge AI & TinyML Systems",
        "company": "ETH Zurich - IIS Lab",
        "institution_or_company": "ETH Zurich",
        "location": "Zurich",
        "country": "Switzerland",
        "link": "https://pbl.ee.ethz.ch/",
        "source": "ETH PBL Lab",
        "deadline": "2026-11-15",
        "status": "Open",
        "degree_level": "MSc / PhD",
        "funding_type": "Fully Funded",
        "professor_name": "Prof. Luca Benini",
        "lab_name": "Integrated Systems Laboratory (IIS / PULP Platform)",
        "lab_website": "https://pulp-platform.org/",
        "research_domain": "TinyML, Edge Computing, RISC-V, Embedded AI",
        "stipend_amount": "CHF 55,000 - 75,000 / year (Standard Swiss RA salary)",
        "requirements": "Solid understanding of computer architecture, RISC-V extensions, and quantization techniques.",
        "priority": "Top",
        "match_score": 95,
        "assistantship": "RA",
        "competition": "High",
        "posted_date": "2026-08-11",
        "keyword": "tinyml, edge ai, risc-v, embedded, eth zurich, ra",
        "description": "Design ultra-low-power neuromorphic architectures and hardware-aware neural network compilers on RISC-V cores."
    },
    {
        "id": "ra-006",
        "category": "ra",
        "title": "Graduate RA: Medical Image Analysis & Generative Models",
        "company": "Vector Institute & U of Toronto",
        "institution_or_company": "University of Toronto",
        "location": "Toronto, ON",
        "country": "Canada",
        "link": "https://vectorinstitute.ai/research/",
        "source": "Vector Institute",
        "deadline": "2026-12-05",
        "status": "Upcoming",
        "degree_level": "MSc / PhD",
        "funding_type": "Fully Funded",
        "professor_name": "Prof. Marzyeh Ghassemi / Prof. Bo Wang",
        "lab_name": "AI for Health Lab",
        "lab_website": "https://vectorinstitute.ai/",
        "research_domain": "Healthcare AI, Diffusion Models, Medical Imaging",
        "stipend_amount": "CAD 34,000 / year + Full Tuition Coverage",
        "requirements": "Strong Python/PyTorch proficiency. Interest in biomedical segmentation, multi-omics, or diffusion models.",
        "priority": "High",
        "match_score": 92,
        "assistantship": "RA",
        "competition": "Medium",
        "posted_date": "2026-08-23",
        "keyword": "healthcare ai, medical imaging, diffusion models, toronto, ra",
        "description": "Develop interpretable generative diffusion models for MRI/CT scan enhancement and disease progression forecasting."
    },
    {
        "id": "grad-001",
        "category": "masters_phd",
        "title": "Erasmus Mundus EMINENT",
        "company": "Erasmus Mundus Consortium",
        "institution_or_company": "Erasmus Mundus Consortium",
        "location": "Europe (Greece/Multi-country)",
        "country": "Europe (Greece/Multi-country)",
        "link": "https://www.applykite.com/scholarships/fully-funded-erasmus-mundus-masters-in-embedded-intelligence-nanotechnology-and-iot-europe-20262028-zov6ru0h2m",
        "source": "Scholarship Tracker Pro",
        "deadline": "March (annual)",
        "status": "Open",
        "degree_level": "Master's",
        "funding_type": "Fully Funded",
        "research_domain": "Computer Science / IoT / Embedded Systems",
        "stipend_amount": "Tuition 100% + \u20ac1400/month stipend + health insurance + travel",
        "requirements": "Bachelor's in relevant field; strong academic record; motivation letter",
        "priority": "Top",
        "match_score": 95,
        "assistantship": "None",
        "competition": "High",
        "keyword": "computer science / iot / embedded systems, europe (greece/multi-country), master's, scholarship",
        "description": "Erasmus Mundus EMINENT offered at Erasmus Mundus Consortium, Europe (Greece/Multi-country). Benefits: Tuition 100% + \u20ac1400/month stipend + health insurance + travel. Eligibility: Bachelor's in relevant field; strong academic record; motivation letter",
        "posted_date": "2026-08-20"
    },
    {
        "id": "grad-002",
        "category": "masters_phd",
        "title": "KAIST Graduate Scholarship",
        "company": "KAIST",
        "institution_or_company": "KAIST",
        "location": "South Korea",
        "country": "South Korea",
        "link": "https://kaistscholarship.com/graduate-scholarship/",
        "source": "Scholarship Tracker Pro",
        "deadline": "Varies by semester",
        "status": "Open",
        "degree_level": "Master's",
        "funding_type": "Fully Funded",
        "research_domain": "Engineering / IoT / Science",
        "stipend_amount": "Full tuition + 350000 KRW/month",
        "requirements": "Bachelor's in relevant field; all intl students eligible on admission",
        "priority": "Medium",
        "match_score": 85,
        "assistantship": "RA",
        "competition": "Medium",
        "keyword": "engineering / iot / science, south korea, master's, scholarship",
        "description": "KAIST Graduate Scholarship offered at KAIST, South Korea. Benefits: Full tuition + 350000 KRW/month. Eligibility: Bachelor's in relevant field; all intl students eligible on admission",
        "posted_date": "2026-08-20"
    },
    {
        "id": "grad-003",
        "category": "masters_phd",
        "title": "MEXT Scholarship (Japanese Govt)",
        "company": "Various Japanese Universities",
        "institution_or_company": "Various Japanese Universities",
        "location": "Japan",
        "country": "Japan",
        "link": "https://www.studyinjapan.go.jp/en/smap-stopj-applications-702.html",
        "source": "Scholarship Tracker Pro",
        "deadline": "Apr-Jun (Embassy) / Nov (Univ)",
        "status": "Open",
        "degree_level": "Master's",
        "funding_type": "Fully Funded",
        "research_domain": "Engineering / Science / Technology",
        "stipend_amount": "Full tuition + 143000 JPY/month + airfare",
        "requirements": "Bachelor's degree; under 35; good academic record",
        "priority": "Top",
        "match_score": 95,
        "assistantship": "None",
        "competition": "High",
        "keyword": "engineering / science / technology, japan, master's, scholarship",
        "description": "MEXT Scholarship (Japanese Govt) offered at Various Japanese Universities, Japan. Benefits: Full tuition + 143000 JPY/month + airfare. Eligibility: Bachelor's degree; under 35; good academic record",
        "posted_date": "2026-08-20"
    },
    {
        "id": "grad-004",
        "category": "masters_phd",
        "title": "Commonwealth Master's Scholarships",
        "company": "Commonwealth Scholarship Commission",
        "institution_or_company": "Commonwealth Scholarship Commission",
        "location": "United Kingdom",
        "country": "United Kingdom",
        "link": "https://cscuk.fcdo.gov.uk/scholarships/commonwealth-masters-scholarships",
        "source": "Scholarship Tracker Pro",
        "deadline": "Dec-Jan (annual)",
        "status": "Open",
        "degree_level": "Master's",
        "funding_type": "Fully Funded",
        "research_domain": "All Subjects (incl. Engineering)",
        "stipend_amount": "Full tuition + living allowance + airfare + thesis grant",
        "requirements": "Commonwealth country citizen (Bangladesh eligible); cannot self-fund",
        "priority": "Top",
        "match_score": 95,
        "assistantship": "None",
        "competition": "High",
        "keyword": "all subjects (incl. engineering), united kingdom, master's, scholarship",
        "description": "Commonwealth Master's Scholarships offered at Commonwealth Scholarship Commission, United Kingdom. Benefits: Full tuition + living allowance + airfare + thesis grant. Eligibility: Commonwealth country citizen (Bangladesh eligible); cannot self-fund",
        "posted_date": "2026-08-20"
    },
    {
        "id": "grad-005",
        "category": "masters_phd",
        "title": "DAAD EPOS Scholarship",
        "company": "DAAD / German Universities",
        "institution_or_company": "DAAD / German Universities",
        "location": "Germany",
        "country": "Germany",
        "link": "https://www.daad.de/en/information-services-for-higher-education-institutions/further-information-on-daad-programmes/epos/",
        "source": "Scholarship Tracker Pro",
        "deadline": "Oct-Nov (annual)",
        "status": "Open",
        "degree_level": "Master's",
        "funding_type": "Fully Funded",
        "research_domain": "Engineering / Development-Related",
        "stipend_amount": "No tuition + \u20ac934/month + insurance + travel",
        "requirements": "Bachelor's + 2 yrs work exp preferred; developing country",
        "priority": "Medium",
        "match_score": 85,
        "assistantship": "None",
        "competition": "Medium",
        "keyword": "engineering / development-related, germany, master's, scholarship",
        "description": "DAAD EPOS Scholarship offered at DAAD / German Universities, Germany. Benefits: No tuition + \u20ac934/month + insurance + travel. Eligibility: Bachelor's + 2 yrs work exp preferred; developing country",
        "posted_date": "2026-08-20"
    },
    {
        "id": "grad-006",
        "category": "masters_phd",
        "title": "Chevening Scholarship",
        "company": "UK Government (FCDO)",
        "institution_or_company": "UK Government (FCDO)",
        "location": "United Kingdom",
        "country": "United Kingdom",
        "link": "https://www.chevening.org/scholarships/",
        "source": "Scholarship Tracker Pro",
        "deadline": "Aug-Nov (annual)",
        "status": "Open",
        "degree_level": "Master's",
        "funding_type": "Fully Funded",
        "research_domain": "All Subjects (incl. Engineering)",
        "stipend_amount": "Full tuition + monthly stipend + travel + thesis grant",
        "requirements": "Bachelor's; 2+ yrs work experience; leadership potential",
        "priority": "Top",
        "match_score": 95,
        "assistantship": "None",
        "competition": "High",
        "keyword": "all subjects (incl. engineering), united kingdom, master's, scholarship",
        "description": "Chevening Scholarship offered at UK Government (FCDO), United Kingdom. Benefits: Full tuition + monthly stipend + travel + thesis grant. Eligibility: Bachelor's; 2+ yrs work experience; leadership potential",
        "posted_date": "2026-08-20"
    },
    {
        "id": "grad-007",
        "category": "masters_phd",
        "title": "Commonwealth Shared Scholarships",
        "company": "CSC + UK Universities",
        "institution_or_company": "CSC + UK Universities",
        "location": "United Kingdom",
        "country": "United Kingdom",
        "link": "https://cscuk.fcdo.gov.uk/scholarships/commonwealth-shared-scholarships",
        "source": "Scholarship Tracker Pro",
        "deadline": "Dec-Jan (annual)",
        "status": "Open",
        "degree_level": "Master's",
        "funding_type": "Fully Funded",
        "research_domain": "Development-related subjects",
        "stipend_amount": "Full tuition + living allowance + airfare",
        "requirements": "Commonwealth developing country; not previously studied in dev country",
        "priority": "Medium",
        "match_score": 85,
        "assistantship": "None",
        "competition": "Medium",
        "keyword": "development-related subjects, united kingdom, master's, scholarship",
        "description": "Commonwealth Shared Scholarships offered at CSC + UK Universities, United Kingdom. Benefits: Full tuition + living allowance + airfare. Eligibility: Commonwealth developing country; not previously studied in dev country",
        "posted_date": "2026-08-20"
    },
    {
        "id": "grad-008",
        "category": "masters_phd",
        "title": "ADB-Japan Scholarship Program",
        "company": "Asian Development Bank",
        "institution_or_company": "Asian Development Bank",
        "location": "Asia-Pacific / USA",
        "country": "Asia-Pacific / USA",
        "link": "https://www.adb.org/what-we-do/education/programs/japan-scholarship-program",
        "source": "Scholarship Tracker Pro",
        "deadline": "Varies by university",
        "status": "Open",
        "degree_level": "Master's",
        "funding_type": "Fully Funded",
        "research_domain": "Engineering / Technology / Economics",
        "stipend_amount": "Full tuition + monthly stipend + travel + books",
        "requirements": "ADB borrowing member (Bangladesh qualifies); bachelor's degree",
        "priority": "Medium",
        "match_score": 85,
        "assistantship": "None",
        "competition": "Medium",
        "keyword": "engineering / technology / economics, asia-pacific / usa, master's, scholarship",
        "description": "ADB-Japan Scholarship Program offered at Asian Development Bank, Asia-Pacific / USA. Benefits: Full tuition + monthly stipend + travel + books. Eligibility: ADB borrowing member (Bangladesh qualifies); bachelor's degree",
        "posted_date": "2026-08-20"
    },
    {
        "id": "grad-009",
        "category": "masters_phd",
        "title": "Tokyo Tech MEXT Scholarship",
        "company": "Tokyo Institute of Technology",
        "institution_or_company": "Tokyo Institute of Technology",
        "location": "Japan",
        "country": "Japan",
        "link": "https://www.titech.ac.jp/english/0/admissions/prospective-students",
        "source": "Scholarship Tracker Pro",
        "deadline": "Nov-Dec (University Rec)",
        "status": "Open",
        "degree_level": "Master's",
        "funding_type": "Fully Funded",
        "research_domain": "Engineering / Science / Technology",
        "stipend_amount": "Full tuition + 143000 JPY/month + airfare",
        "requirements": "Bachelor's degree; research proposal; supervisor match",
        "priority": "Top",
        "match_score": 95,
        "assistantship": "RA",
        "competition": "High",
        "keyword": "engineering / science / technology, japan, master's, scholarship",
        "description": "Tokyo Tech MEXT Scholarship offered at Tokyo Institute of Technology, Japan. Benefits: Full tuition + 143000 JPY/month + airfare. Eligibility: Bachelor's degree; research proposal; supervisor match",
        "posted_date": "2026-08-20"
    },
    {
        "id": "grad-010",
        "category": "masters_phd",
        "title": "Hokkaido e3 Program (MEXT)",
        "company": "Hokkaido University",
        "institution_or_company": "Hokkaido University",
        "location": "Japan",
        "country": "Japan",
        "link": "https://eprogram.eng.hokudai.ac.jp/e3/scholarships/mext",
        "source": "Scholarship Tracker Pro",
        "deadline": "Nov (University Rec)",
        "status": "Open",
        "degree_level": "Master's",
        "funding_type": "Fully Funded",
        "research_domain": "Engineering (English-taught)",
        "stipend_amount": "Full tuition + 143000 JPY/month + airfare",
        "requirements": "Bachelor's in engineering; English proficiency",
        "priority": "Medium",
        "match_score": 85,
        "assistantship": "RA",
        "competition": "Medium",
        "keyword": "engineering (english-taught), japan, master's, scholarship",
        "description": "Hokkaido e3 Program (MEXT) offered at Hokkaido University, Japan. Benefits: Full tuition + 143000 JPY/month + airfare. Eligibility: Bachelor's in engineering; English proficiency",
        "posted_date": "2026-08-20"
    },
    {
        "id": "grad-011",
        "category": "masters_phd",
        "title": "Erasmus Mundus Manufacturing 4.0 (meta4.0)",
        "company": "Erasmus Mundus Consortium",
        "institution_or_company": "Erasmus Mundus Consortium",
        "location": "Europe (Multi-country)",
        "country": "Europe (Multi-country)",
        "link": "https://daadscholarship.com/manufacturing-4-0-scholarship-2026-erasmus-mundus-joint-program/",
        "source": "Scholarship Tracker Pro",
        "deadline": "Feb-March (annual)",
        "status": "Open",
        "degree_level": "Master's",
        "funding_type": "Fully Funded",
        "research_domain": "Manufacturing / Industry 4.0 / Digital Mfg",
        "stipend_amount": "Full tuition + monthly stipend + travel + insurance",
        "requirements": "Bachelor's in engineering; motivation for smart manufacturing",
        "priority": "Top",
        "match_score": 95,
        "assistantship": "None",
        "competition": "High",
        "keyword": "manufacturing / industry 4.0 / digital mfg, europe (multi-country), master's, scholarship",
        "description": "Erasmus Mundus Manufacturing 4.0 (meta4.0) offered at Erasmus Mundus Consortium, Europe (Multi-country). Benefits: Full tuition + monthly stipend + travel + insurance. Eligibility: Bachelor's in engineering; motivation for smart manufacturing",
        "posted_date": "2026-08-20"
    },
    {
        "id": "grad-012",
        "category": "masters_phd",
        "title": "POSCO Asia Fellowship",
        "company": "POSCO TJ Park Foundation",
        "institution_or_company": "POSCO TJ Park Foundation",
        "location": "South Korea",
        "country": "South Korea",
        "link": "https://opportunitiescorners.com/posco-asia-fellowship-2026/",
        "source": "Scholarship Tracker Pro",
        "deadline": "Varies",
        "status": "Open",
        "degree_level": "Master's",
        "funding_type": "Fully Funded",
        "research_domain": "Engineering / Science / Technology",
        "stipend_amount": "Full tuition + living expenses + airfare",
        "requirements": "Asian country; bachelor's; strong record; under 35",
        "priority": "Medium",
        "match_score": 85,
        "assistantship": "None",
        "competition": "Medium",
        "keyword": "engineering / science / technology, south korea, master's, scholarship",
        "description": "POSCO Asia Fellowship offered at POSCO TJ Park Foundation, South Korea. Benefits: Full tuition + living expenses + airfare. Eligibility: Asian country; bachelor's; strong record; under 35",
        "posted_date": "2026-08-20"
    },
    {
        "id": "grad-013",
        "category": "masters_phd",
        "title": "TU/e Graduate Scholarship",
        "company": "Eindhoven University of Technology",
        "institution_or_company": "Eindhoven University of Technology",
        "location": "Netherlands",
        "country": "Netherlands",
        "link": "https://www.tue.nl/en/education/become-a-tue-student/masters-programs/scholarships",
        "source": "Scholarship Tracker Pro",
        "deadline": "Apr-May",
        "status": "Open",
        "degree_level": "Master's",
        "funding_type": "Fully Funded",
        "research_domain": "Engineering / AI / Data Science",
        "stipend_amount": "Tuition waiver + stipend (varies)",
        "requirements": "Bachelor's in relevant field; excellent record; non-EU/EEA",
        "priority": "Top",
        "match_score": 95,
        "assistantship": "None",
        "competition": "High",
        "keyword": "engineering / ai / data science, netherlands, master's, scholarship",
        "description": "TU/e Graduate Scholarship offered at Eindhoven University of Technology, Netherlands. Benefits: Tuition waiver + stipend (varies). Eligibility: Bachelor's in relevant field; excellent record; non-EU/EEA",
        "posted_date": "2026-08-20"
    },
    {
        "id": "grad-014",
        "category": "masters_phd",
        "title": "University of Twente Scholarship",
        "company": "University of Twente",
        "institution_or_company": "University of Twente",
        "location": "Netherlands",
        "country": "Netherlands",
        "link": "https://www.utwente.nl/en/education/scholarship-finder/university-of-twente-scholarship/",
        "source": "Scholarship Tracker Pro",
        "deadline": "May 1 2026",
        "status": "Open",
        "degree_level": "Master's",
        "funding_type": "Partially Funded",
        "research_domain": "Engineering / Technology / Science",
        "stipend_amount": "\u20ac3000\u2013\u20ac22000 towards tuition",
        "requirements": "Non-EU/EEA student; strong academic record",
        "priority": "Medium",
        "match_score": 85,
        "assistantship": "None",
        "competition": "Medium",
        "keyword": "engineering / technology / science, netherlands, master's, scholarship",
        "description": "University of Twente Scholarship offered at University of Twente, Netherlands. Benefits: \u20ac3000\u2013\u20ac22000 towards tuition. Eligibility: Non-EU/EEA student; strong academic record",
        "posted_date": "2026-08-20"
    },
    {
        "id": "grad-015",
        "category": "masters_phd",
        "title": "RWTH Aachen Global Talent Scholarship",
        "company": "RWTH International Academy",
        "institution_or_company": "RWTH International Academy",
        "location": "Germany",
        "country": "Germany",
        "link": "https://www.academy.rwth-aachen.de/en/services/scholarships",
        "source": "Scholarship Tracker Pro",
        "deadline": "Varies",
        "status": "Open",
        "degree_level": "Master's",
        "funding_type": "Partially Funded",
        "research_domain": "Engineering / Management & Engineering",
        "stipend_amount": "Tuition reduction or stipend support",
        "requirements": "Bachelor's in engineering; strong record; diversity factor",
        "priority": "Medium",
        "match_score": 85,
        "assistantship": "None",
        "competition": "Medium",
        "keyword": "engineering / management & engineering, germany, master's, scholarship",
        "description": "RWTH Aachen Global Talent Scholarship offered at RWTH International Academy, Germany. Benefits: Tuition reduction or stipend support. Eligibility: Bachelor's in engineering; strong record; diversity factor",
        "posted_date": "2026-08-20"
    },
    {
        "id": "grad-016",
        "category": "masters_phd",
        "title": "UMass Lowell Global Engineering Leaders",
        "company": "University of Massachusetts Lowell",
        "institution_or_company": "University of Massachusetts Lowell",
        "location": "USA",
        "country": "USA",
        "link": "https://uml.edu/grad/costs/global-engineering-leaders.aspx",
        "source": "Scholarship Tracker Pro",
        "deadline": "Priority deadlines",
        "status": "Open",
        "degree_level": "Master's",
        "funding_type": "Partially Funded",
        "research_domain": "Engineering (various)",
        "stipend_amount": "$20000 ($5000/semester \u00d7 4)",
        "requirements": "International student; Master's in engineering; academic excellence",
        "priority": "Medium",
        "match_score": 85,
        "assistantship": "RA",
        "competition": "Medium",
        "keyword": "engineering (various), usa, master's, scholarship",
        "description": "UMass Lowell Global Engineering Leaders offered at University of Massachusetts Lowell, USA. Benefits: $20000 ($5000/semester \u00d7 4). Eligibility: International student; Master's in engineering; academic excellence",
        "posted_date": "2026-08-20"
    },
    {
        "id": "grad-017",
        "category": "masters_phd",
        "title": "GREAT Scholarships (UK)",
        "company": "British Council + UK Universities",
        "institution_or_company": "British Council + UK Universities",
        "location": "United Kingdom",
        "country": "United Kingdom",
        "link": "https://study-uk.britishcouncil.org/scholarships/great-scholarships",
        "source": "Scholarship Tracker Pro",
        "deadline": "Varies",
        "status": "Open",
        "degree_level": "Master's",
        "funding_type": "Partially Funded",
        "research_domain": "Varies by university",
        "stipend_amount": "\u00a310000 tuition fee reduction",
        "requirements": "National of Bangladesh; overseas student; accepted to Master's",
        "priority": "Low",
        "match_score": 85,
        "assistantship": "None",
        "competition": "Low",
        "keyword": "varies by university, united kingdom, master's, scholarship",
        "description": "GREAT Scholarships (UK) offered at British Council + UK Universities, United Kingdom. Benefits: \u00a310000 tuition fee reduction. Eligibility: National of Bangladesh; overseas student; accepted to Master's",
        "posted_date": "2026-08-20"
    },
    {
        "id": "grad-018",
        "category": "masters_phd",
        "title": "Cranfield GREAT Scholarship Bangladesh",
        "company": "Cranfield University + British Council",
        "institution_or_company": "Cranfield University + British Council",
        "location": "United Kingdom",
        "country": "United Kingdom",
        "link": "https://www.cranfield.ac.uk/funding/funding-opportunities/great-cranfield-university-scholarship-bangladesh",
        "source": "Scholarship Tracker Pro",
        "deadline": "May 18 2026",
        "status": "Open",
        "degree_level": "Master's",
        "funding_type": "Partially Funded",
        "research_domain": "Engineering / Technology / Management",
        "stipend_amount": "\u00a310000 towards tuition",
        "requirements": "Bangladeshi passport holder and resident",
        "priority": "Low",
        "match_score": 85,
        "assistantship": "None",
        "competition": "Low",
        "keyword": "engineering / technology / management, united kingdom, master's, scholarship",
        "description": "Cranfield GREAT Scholarship Bangladesh offered at Cranfield University + British Council, United Kingdom. Benefits: \u00a310000 towards tuition. Eligibility: Bangladeshi passport holder and resident",
        "posted_date": "2026-08-20"
    },
    {
        "id": "grad-019",
        "category": "masters_phd",
        "title": "Sussex Bangladesh Scholarship",
        "company": "University of Sussex",
        "institution_or_company": "University of Sussex",
        "location": "United Kingdom",
        "country": "United Kingdom",
        "link": "https://www.sussex.ac.uk/study/fees-funding/masters-scholarships/view/1765-Sussex-Bangladesh-Scholarship-Masters",
        "source": "Scholarship Tracker Pro",
        "deadline": "Varies",
        "status": "Open",
        "degree_level": "Master's",
        "funding_type": "Partially Funded",
        "research_domain": "All Subjects",
        "stipend_amount": "\u00a34000 tuition fee reduction",
        "requirements": "National of Bangladesh; overseas; self-financing",
        "priority": "Low",
        "match_score": 85,
        "assistantship": "None",
        "competition": "Low",
        "keyword": "all subjects, united kingdom, master's, scholarship",
        "description": "Sussex Bangladesh Scholarship offered at University of Sussex, United Kingdom. Benefits: \u00a34000 tuition fee reduction. Eligibility: National of Bangladesh; overseas; self-financing",
        "posted_date": "2026-08-20"
    },
    {
        "id": "grad-020",
        "category": "masters_phd",
        "title": "IUJ Scholarships",
        "company": "International University of Japan",
        "institution_or_company": "International University of Japan",
        "location": "Japan",
        "country": "Japan",
        "link": "https://www.iuj.ac.jp/admis/scholarship-financial-aid/",
        "source": "Scholarship Tracker Pro",
        "deadline": "Varies",
        "status": "Open",
        "degree_level": "Master's",
        "funding_type": "Fully Funded",
        "research_domain": "Multiple Fields (incl. Technology)",
        "stipend_amount": "Full tuition + living stipend",
        "requirements": "International student; bachelor's; English proficiency",
        "priority": "Low",
        "match_score": 85,
        "assistantship": "None",
        "competition": "Low",
        "keyword": "multiple fields (incl. technology), japan, master's, scholarship",
        "description": "IUJ Scholarships offered at International University of Japan, Japan. Benefits: Full tuition + living stipend. Eligibility: International student; bachelor's; English proficiency",
        "posted_date": "2026-08-20"
    },
    {
        "id": "grad-021",
        "category": "masters_phd",
        "title": "Erasmus Mundus EMAI",
        "company": "Erasmus Mundus Consortium",
        "institution_or_company": "Erasmus Mundus Consortium",
        "location": "Europe (Spain/Italy/Netherlands/Slovenia)",
        "country": "Europe (Spain/Italy/Netherlands/Slovenia)",
        "link": "https://www.upf.edu/web/masters/2_preinscripcio",
        "source": "Scholarship Tracker Pro",
        "deadline": "January (annual)",
        "status": "Open",
        "degree_level": "Master's",
        "funding_type": "Fully Funded",
        "research_domain": "Artificial Intelligence / ML / Robotics / Cybersecurity",
        "stipend_amount": "Tuition 100% + \u20ac1400/month + travel \u20ac2000-3000/yr + insurance + \u20ac1000 installation",
        "requirements": "Bachelor's \u2265180 ECTS in ICT/Engineering/Physics/Math; IELTS 6.5 or TOEFL 90",
        "priority": "Top",
        "match_score": 95,
        "assistantship": "None",
        "competition": "High",
        "keyword": "artificial intelligence / ml / robotics / cybersecurity, europe (spain/italy/netherlands/slovenia), master's, scholarship",
        "description": "Erasmus Mundus EMAI offered at Erasmus Mundus Consortium, Europe (Spain/Italy/Netherlands/Slovenia). Benefits: Tuition 100% + \u20ac1400/month + travel \u20ac2000-3000/yr + insurance + \u20ac1000 installation. Eligibility: Bachelor's \u2265180 ECTS in ICT/Engineering/Physics/Math; IELTS 6.5 or TOEFL 90",
        "posted_date": "2026-08-20"
    },
    {
        "id": "grad-022",
        "category": "masters_phd",
        "title": "Erasmus Mundus CyberMACS",
        "company": "Erasmus Mundus Consortium",
        "institution_or_company": "Erasmus Mundus Consortium",
        "location": "Europe (Turkey/Germany/North Macedonia)",
        "country": "Europe (Turkey/Germany/North Macedonia)",
        "link": "https://cybermacs.eu/apply/",
        "source": "Scholarship Tracker Pro",
        "deadline": "December (annual)",
        "status": "Open",
        "degree_level": "Master's",
        "funding_type": "Fully Funded",
        "research_domain": "Applied Cybersecurity / Network Security / Cryptography",
        "stipend_amount": "Tuition 100% + \u20ac1400/month + travel \u20ac2000-3000/yr + insurance + \u20ac1000 installation",
        "requirements": "Bachelor's in CS/Math or related; good grades; English proficiency",
        "priority": "Top",
        "match_score": 95,
        "assistantship": "None",
        "competition": "High",
        "keyword": "applied cybersecurity / network security / cryptography, europe (turkey/germany/north macedonia), master's, scholarship",
        "description": "Erasmus Mundus CyberMACS offered at Erasmus Mundus Consortium, Europe (Turkey/Germany/North Macedonia). Benefits: Tuition 100% + \u20ac1400/month + travel \u20ac2000-3000/yr + insurance + \u20ac1000 installation. Eligibility: Bachelor's in CS/Math or related; good grades; English proficiency",
        "posted_date": "2026-08-20"
    },
    {
        "id": "grad-023",
        "category": "masters_phd",
        "title": "Erasmus Mundus CYBERUS",
        "company": "Erasmus Mundus Consortium",
        "institution_or_company": "Erasmus Mundus Consortium",
        "location": "Europe (France/Luxembourg/Estonia/Belgium)",
        "country": "Europe (France/Luxembourg/Estonia/Belgium)",
        "link": "https://cyberus-emjm.eu/",
        "source": "Scholarship Tracker Pro",
        "deadline": "February (annual)",
        "status": "Open",
        "degree_level": "Master's",
        "funding_type": "Fully Funded",
        "research_domain": "Cybersecurity",
        "stipend_amount": "Tuition 100% + \u20ac1400/month + travel + insurance",
        "requirements": "Bachelor's in CS/Engineering; English proficiency",
        "priority": "Top",
        "match_score": 95,
        "assistantship": "None",
        "competition": "High",
        "keyword": "cybersecurity, europe (france/luxembourg/estonia/belgium), master's, scholarship",
        "description": "Erasmus Mundus CYBERUS offered at Erasmus Mundus Consortium, Europe (France/Luxembourg/Estonia/Belgium). Benefits: Tuition 100% + \u20ac1400/month + travel + insurance. Eligibility: Bachelor's in CS/Engineering; English proficiency",
        "posted_date": "2026-08-20"
    },
    {
        "id": "grad-024",
        "category": "masters_phd",
        "title": "Erasmus Mundus CoDaS",
        "company": "Erasmus Mundus Consortium",
        "institution_or_company": "Erasmus Mundus Consortium",
        "location": "Europe (Finland/Portugal/Germany/Spain/France)",
        "country": "Europe (Finland/Portugal/Germany/Spain/France)",
        "link": "https://www.unite-codas-master.eu/admission.html#apply",
        "source": "Scholarship Tracker Pro",
        "deadline": "January (annual)",
        "status": "Open",
        "degree_level": "Master's",
        "funding_type": "Fully Funded",
        "research_domain": "Communications Engineering / Data Science / IoT / 5G-6G",
        "stipend_amount": "Tuition 100% + \u20ac1400/month + travel + insurance",
        "requirements": "Bachelor's in Engineering/CS/EE/Data Science; good GPA; English proficiency",
        "priority": "Top",
        "match_score": 95,
        "assistantship": "None",
        "competition": "High",
        "keyword": "communications engineering / data science / iot / 5g-6g, europe (finland/portugal/germany/spain/france), master's, scholarship",
        "description": "Erasmus Mundus CoDaS offered at Erasmus Mundus Consortium, Europe (Finland/Portugal/Germany/Spain/France). Benefits: Tuition 100% + \u20ac1400/month + travel + insurance. Eligibility: Bachelor's in Engineering/CS/EE/Data Science; good GPA; English proficiency",
        "posted_date": "2026-08-20"
    },
    {
        "id": "grad-025",
        "category": "masters_phd",
        "title": "Erasmus Mundus EMSSE",
        "company": "Erasmus Mundus Consortium",
        "institution_or_company": "Erasmus Mundus Consortium",
        "location": "Europe (France/Italy/Spain/Albania)",
        "country": "Europe (France/Italy/Spain/Albania)",
        "link": "https://emsse-master.eu/",
        "source": "Scholarship Tracker Pro",
        "deadline": "March (annual)",
        "status": "Open",
        "degree_level": "Master's",
        "funding_type": "Fully Funded",
        "research_domain": "Sustainable Systems Engineering / Smart Manufacturing",
        "stipend_amount": "Tuition 100% + \u20ac1400/month + travel + insurance",
        "requirements": "Bachelor's in engineering; English proficiency",
        "priority": "Medium",
        "match_score": 85,
        "assistantship": "None",
        "competition": "Medium",
        "keyword": "sustainable systems engineering / smart manufacturing, europe (france/italy/spain/albania), master's, scholarship",
        "description": "Erasmus Mundus EMSSE offered at Erasmus Mundus Consortium, Europe (France/Italy/Spain/Albania). Benefits: Tuition 100% + \u20ac1400/month + travel + insurance. Eligibility: Bachelor's in engineering; English proficiency",
        "posted_date": "2026-08-20"
    },
    {
        "id": "grad-026",
        "category": "masters_phd",
        "title": "UNIST Graduate Scholarship",
        "company": "Ulsan National Institute of Science and Technology",
        "institution_or_company": "Ulsan National Institute of Science and Technology",
        "location": "South Korea",
        "country": "South Korea",
        "link": "https://admg-intl.unist.ac.kr/",
        "source": "Scholarship Tracker Pro",
        "deadline": "Jul 2026 (1st intake) / Oct 2026 (2nd intake)",
        "status": "Open",
        "degree_level": "Master's",
        "funding_type": "Fully Funded",
        "research_domain": "Engineering / AI / Computer Science / Materials / Energy",
        "stipend_amount": "Full tuition (KRW 3.84M/sem) + KRW 800K-1.44M/month + dormitory",
        "requirements": "Bachelor's degree; TOEFL/IELTS; study plan + personal statement",
        "priority": "Medium",
        "match_score": 85,
        "assistantship": "RA",
        "competition": "Medium",
        "keyword": "engineering / ai / computer science / materials / energy, south korea, master's, scholarship",
        "description": "UNIST Graduate Scholarship offered at Ulsan National Institute of Science and Technology, South Korea. Benefits: Full tuition (KRW 3.84M/sem) + KRW 800K-1.44M/month + dormitory. Eligibility: Bachelor's degree; TOEFL/IELTS; study plan + personal statement",
        "posted_date": "2026-08-20"
    },
    {
        "id": "grad-027",
        "category": "masters_phd",
        "title": "GIST International Scholarship",
        "company": "Gwangju Institute of Science and Technology",
        "institution_or_company": "Gwangju Institute of Science and Technology",
        "location": "South Korea",
        "country": "South Korea",
        "link": "https://www.gist.ac.kr/en/html/sub05/050201.html",
        "source": "Scholarship Tracker Pro",
        "deadline": "Varies by semester",
        "status": "Open",
        "degree_level": "Master's",
        "funding_type": "Fully Funded",
        "research_domain": "Engineering / AI / Science / Technology",
        "stipend_amount": "Full tuition + KRW 140K/month + KRW 120K intl allowance + research stipend",
        "requirements": "Bachelor's degree; English proficiency; research interest",
        "priority": "Medium",
        "match_score": 85,
        "assistantship": "RA",
        "competition": "Medium",
        "keyword": "engineering / ai / science / technology, south korea, master's, scholarship",
        "description": "GIST International Scholarship offered at Gwangju Institute of Science and Technology, South Korea. Benefits: Full tuition + KRW 140K/month + KRW 120K intl allowance + research stipend. Eligibility: Bachelor's degree; English proficiency; research interest",
        "posted_date": "2026-08-20"
    },
    {
        "id": "grad-028",
        "category": "masters_phd",
        "title": "Global Korea Scholarship (GKS)",
        "company": "Korean Government (NIIED)",
        "institution_or_company": "Korean Government (NIIED)",
        "location": "South Korea",
        "country": "South Korea",
        "link": "https://www.studyinkorea.go.kr/en/sub/gks/allnew_invite.do",
        "source": "Scholarship Tracker Pro",
        "deadline": "Feb-Mar (Embassy) / Mar-Apr (University)",
        "status": "Open",
        "degree_level": "Master's",
        "funding_type": "Fully Funded",
        "research_domain": "All Subjects (incl. Engineering)",
        "stipend_amount": "Full tuition + KRW 1M/month + airfare + settlement + insurance + Korean language training",
        "requirements": "Under 40; bachelor's; GPA 80%+; developing country citizen (Bangladesh eligible)",
        "priority": "Top",
        "match_score": 95,
        "assistantship": "None",
        "competition": "High",
        "keyword": "all subjects (incl. engineering), south korea, master's, scholarship",
        "description": "Global Korea Scholarship (GKS) offered at Korean Government (NIIED), South Korea. Benefits: Full tuition + KRW 1M/month + airfare + settlement + insurance + Korean language training. Eligibility: Under 40; bachelor's; GPA 80%+; developing country citizen (Bangladesh eligible)",
        "posted_date": "2026-08-20"
    },
    {
        "id": "grad-029",
        "category": "masters_phd",
        "title": "KOICA Bangladesh Scholarship",
        "company": "KOICA/Korean Government",
        "institution_or_company": "KOICA/Korean Government",
        "location": "South Korea",
        "country": "South Korea",
        "link": "https://koicascholarship.org/koica-bangladesh-scholarship/",
        "source": "Scholarship Tracker Pro",
        "deadline": "March-April 2026",
        "status": "Open",
        "degree_level": "Master's",
        "funding_type": "Fully Funded",
        "research_domain": "Development Studies / Public Administration / Engineering",
        "stipend_amount": "Full tuition + stipend + airfare + insurance + settling-in allowance",
        "requirements": "Bangladeshi citizen; government/NGO employee preferred; bachelor's degree",
        "priority": "Medium",
        "match_score": 85,
        "assistantship": "None",
        "competition": "Medium",
        "keyword": "development studies / public administration / engineering, south korea, master's, scholarship",
        "description": "KOICA Bangladesh Scholarship offered at KOICA/Korean Government, South Korea. Benefits: Full tuition + stipend + airfare + insurance + settling-in allowance. Eligibility: Bangladeshi citizen; government/NGO employee preferred; bachelor's degree",
        "posted_date": "2026-08-20"
    },
    {
        "id": "grad-030",
        "category": "masters_phd",
        "title": "CSC Scholarship - Beijing Institute of Technology",
        "company": "Beijing Institute of Technology (BIT)",
        "institution_or_company": "Beijing Institute of Technology (BIT)",
        "location": "China",
        "country": "China",
        "link": "https://chinascholarshipcouncil.com/beijing-institute-of-technology-csc-scholarship/",
        "source": "Scholarship Tracker Pro",
        "deadline": "March-April 2026",
        "status": "Open",
        "degree_level": "Master's",
        "funding_type": "Fully Funded",
        "research_domain": "Computer Science / Engineering / Sciences",
        "stipend_amount": "Tuition + free accommodation + insurance + CNY 3000/month (Master's)",
        "requirements": "Bachelor's degree; under 35; English or Chinese proficiency",
        "priority": "Medium",
        "match_score": 85,
        "assistantship": "None",
        "competition": "Medium",
        "keyword": "computer science / engineering / sciences, china, master's, scholarship",
        "description": "CSC Scholarship - Beijing Institute of Technology offered at Beijing Institute of Technology (BIT), China. Benefits: Tuition + free accommodation + insurance + CNY 3000/month (Master's). Eligibility: Bachelor's degree; under 35; English or Chinese proficiency",
        "posted_date": "2026-08-20"
    },
    {
        "id": "grad-031",
        "category": "masters_phd",
        "title": "Fulbright Foreign Student Program",
        "company": "U.S. Department of State / IIE",
        "institution_or_company": "U.S. Department of State / IIE",
        "location": "USA",
        "country": "USA",
        "link": "https://bd.usembassy.gov/call-for-applications-for-the-2026-2027-fulbright-foreign-student-program/",
        "source": "Scholarship Tracker Pro",
        "deadline": "May-June 2026 (for 2027-28 cohort)",
        "status": "Open",
        "degree_level": "Master's",
        "funding_type": "Fully Funded",
        "research_domain": "All Subjects (incl. Engineering)",
        "stipend_amount": "Full tuition + living stipend + airfare + health insurance + book allowance",
        "requirements": "Bangladeshi citizen; bachelor's; 3+ yrs work/teaching exp preferred; leadership",
        "priority": "Top",
        "match_score": 95,
        "assistantship": "None",
        "competition": "High",
        "keyword": "all subjects (incl. engineering), usa, master's, scholarship",
        "description": "Fulbright Foreign Student Program offered at U.S. Department of State / IIE, USA. Benefits: Full tuition + living stipend + airfare + health insurance + book allowance. Eligibility: Bangladeshi citizen; bachelor's; 3+ yrs work/teaching exp preferred; leadership",
        "posted_date": "2026-08-20"
    },
    {
        "id": "grad-032",
        "category": "masters_phd",
        "title": "University of Bologna Scholarship",
        "company": "University of Bologna",
        "institution_or_company": "University of Bologna",
        "location": "Italy",
        "country": "Italy",
        "link": "https://www.unibo.it/en/services-and-opportunities/study-grants-and-subsidies/grants-for-international-students",
        "source": "Scholarship Tracker Pro",
        "deadline": "March (annual)",
        "status": "Open",
        "degree_level": "Master's",
        "funding_type": "Fully Funded",
        "research_domain": "All Subjects (incl. Engineering)",
        "stipend_amount": "Tuition waiver + \u20ac11000/year stipend",
        "requirements": "Bachelor's degree; SAT/GRE score; English proficiency",
        "priority": "Medium",
        "match_score": 85,
        "assistantship": "None",
        "competition": "Medium",
        "keyword": "all subjects (incl. engineering), italy, master's, scholarship",
        "description": "University of Bologna Scholarship offered at University of Bologna, Italy. Benefits: Tuition waiver + \u20ac11000/year stipend. Eligibility: Bachelor's degree; SAT/GRE score; English proficiency",
        "posted_date": "2026-08-20"
    }
]
